### ISSUE TITLE
Can't install Android version "it was made for an older version of Android"

### ISSUE THREAD

**Issue by murkle** [gailasgteach/TiltMaze#1]
I can't install this on Android 13:
https://play.google.com/store/apps/details?id=com.asgteach.accelerometer.TiltMaze

![image](https://github.com/gailasgteach/TiltMaze/assets/814957/12f53279-37ee-4d36-981e-b47425459f6c)

**Comment by gailasgteach** [comment]
TiltMaze has been updated to target new versions of Android (target SDK 33). Issue should be addressed.
